name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.61.0
          cache: true
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          OPENAI_API_ENDPOINT: https://mkp-api.fptcloud.com
          MODEL: Qwen2.5-Coder-32B-Instruct
